Repository alibaba/Sentinel, pull requests merged in 2019-06, with the labels that each got.

#806 docs(Sentinel Dashborad multi-data source adapter）
  doc/awesome-sentinel.md
Labels: area/document

#747 com.alibaba.csp.sentinel.node.StatisticNode#curThreadNum
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/node/StatisticNode.java
  sentinel-core/src/test/java/com/alibaba/csp/sentinel/node/StatisticNodeTest.java
Labels: to review

#723 use calculateTimeIdx to calculate idx
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/node/StatisticNode.java
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/statistic/base/LeapArray.java
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/statistic/metric/ArrayMetric.java
Labels: to review

#800 sentinel-dashboard add version backend API for issue 728
  sentinel-dashboard/pom.xml
  sentinel-dashboard/src/main/java/com/alibaba/csp/sentinel/dashboard/controller/VersionController.java
  sentinel-dashboard/src/main/resources/application.properties
Labels: area/dashboard

#781 Feature/sentinel pigeon adapter
  doc/awesome-sentinel.md
Labels: area/integrations, to review

#817 Fix unknown command issue in sentinel-transport-netty-http module
  pom.xml
  sentinel-transport/sentinel-transport-netty-http/src/main/java/com/alibaba/csp/sentinel/transport/command/netty/HttpServerHandler.java
  sentinel-transport/sentinel-transport-netty-http/src/test/java/com/alibaba/csp/sentinel/transport/command/handler/MultipleSlashNameCommandTestHandler.java
  sentinel-transport/sentinel-transport-netty-http/src/test/java/com/alibaba/csp/sentinel/transport/command/netty/HttpServerHandlerTest.java
  sentinel-transport/sentinel-transport-netty-http/src/test/java/com/alibaba/csp/sentinel/transport/command/netty/HttpServerInitializerTest.java
  sentinel-transport/sentinel-transport-netty-http/src/test/java/com/alibaba/csp/sentinel/transport/command/netty/HttpServerTest.java
  sentinel-transport/sentinel-transport-netty-http/src/test/resources/META-INF/services/com.alibaba.csp.sentinel.command.CommandHandler
  sentinel-transport/sentinel-transport-simple-http/src/main/java/com/alibaba/csp/sentinel/transport/heartbeat/SimpleHttpHeartbeatSender.java
Labels: to review

#825 adding blog,title:Alibaba Sentinel RESTful 接口流控处理优化
  doc/awesome-sentinel.md
Labels: area/document

#814 Add support for parsing cookie as request items in gateway flow control
  sentinel-adapter/sentinel-api-gateway-adapter-common/src/main/java/com/alibaba/csp/sentinel/adapter/gateway/common/SentinelGatewayConstants.java
  sentinel-adapter/sentinel-api-gateway-adapter-common/src/main/java/com/alibaba/csp/sentinel/adapter/gateway/common/param/GatewayParamParser.java
  sentinel-adapter/sentinel-api-gateway-adapter-common/src/main/java/com/alibaba/csp/sentinel/adapter/gateway/common/param/RequestItemParser.java
  sentinel-adapter/sentinel-api-gateway-adapter-common/src/main/java/com/alibaba/csp/sentinel/adapter/gateway/common/rule/GatewayRuleManager.java
  sentinel-adapter/sentinel-api-gateway-adapter-common/src/test/java/com/alibaba/csp/sentinel/adapter/gateway/common/param/GatewayParamParserTest.java
  sentinel-adapter/sentinel-spring-cloud-gateway-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/gateway/sc/ServerWebExchangeItemParser.java
  sentinel-adapter/sentinel-zuul-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/gateway/zuul/RequestContextItemParser.java
Labels: kind/enhancement, to review

#840 Fix the README to the new metrics writing format
  README.md
Labels: area/document

#845 Improve the edit dialog for FlowRule and ParamFlowRule in Sentinel dashboard
  sentinel-dashboard/src/main/java/com/alibaba/csp/sentinel/dashboard/controller/ParamFlowRuleController.java
  sentinel-dashboard/src/main/java/com/alibaba/csp/sentinel/dashboard/datasource/entity/rule/AbstractRuleEntity.java
  sentinel-dashboard/src/main/java/com/alibaba/csp/sentinel/dashboard/datasource/entity/rule/AuthorityRuleEntity.java
  sentinel-dashboard/src/main/java/com/alibaba/csp/sentinel/dashboard/datasource/entity/rule/ParamFlowRuleEntity.java
  sentinel-dashboard/src/main/webapp/resources/app/scripts/controllers/identity.js
  sentinel-dashboard/src/main/webapp/resources/app/scripts/controllers/param_flow.js
  sentinel-dashboard/src/main/webapp/resources/app/views/dialog/flow-rule-dialog.html
  sentinel-dashboard/src/main/webapp/resources/app/views/dialog/param-flow-rule-dialog.html
Labels: area/dashboard, to review

#838 Fix the bug that numeric overflow might occur when refilling tokens in ParamFlowChecker
  sentinel-extension/sentinel-parameter-flow-control/src/main/java/com/alibaba/csp/sentinel/slots/block/flow/param/ParamFlowChecker.java
  sentinel-extension/sentinel-parameter-flow-control/src/main/java/com/alibaba/csp/sentinel/slots/block/flow/param/ParameterMetric.java
  sentinel-extension/sentinel-parameter-flow-control/src/test/java/com/alibaba/csp/sentinel/slots/block/flow/param/ParamFlowCheckerTest.java
  sentinel-extension/sentinel-parameter-flow-control/src/test/java/com/alibaba/csp/sentinel/slots/block/flow/param/ParamFlowDefaultCheckerTest.java
  sentinel-extension/sentinel-parameter-flow-control/src/test/java/com/alibaba/csp/sentinel/slots/block/flow/param/ParamFlowSlotTest.java
Labels: to review

#842 Add support for request item pattern matching in API gateway flow control
  sentinel-adapter/sentinel-api-gateway-adapter-common/src/main/java/com/alibaba/csp/sentinel/adapter/gateway/common/SentinelGatewayConstants.java
  sentinel-adapter/sentinel-api-gateway-adapter-common/src/main/java/com/alibaba/csp/sentinel/adapter/gateway/common/api/ApiPathPredicateItem.java
  sentinel-adapter/sentinel-api-gateway-adapter-common/src/main/java/com/alibaba/csp/sentinel/adapter/gateway/common/param/GatewayParamParser.java
  sentinel-adapter/sentinel-api-gateway-adapter-common/src/main/java/com/alibaba/csp/sentinel/adapter/gateway/common/param/GatewayRegexCache.java
  sentinel-adapter/sentinel-api-gateway-adapter-common/src/main/java/com/alibaba/csp/sentinel/adapter/gateway/common/rule/GatewayRuleConverter.java
  sentinel-adapter/sentinel-api-gateway-adapter-common/src/main/java/com/alibaba/csp/sentinel/adapter/gateway/common/rule/GatewayRuleManager.java
  sentinel-adapter/sentinel-api-gateway-adapter-common/src/test/java/com/alibaba/csp/sentinel/adapter/gateway/common/param/GatewayParamParserTest.java
  sentinel-adapter/sentinel-api-gateway-adapter-common/src/test/java/com/alibaba/csp/sentinel/adapter/gateway/common/param/GatewayRegexCacheTest.java
  sentinel-adapter/sentinel-spring-cloud-gateway-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/gateway/sc/api/matcher/WebExchangeApiMatcher.java
  sentinel-adapter/sentinel-spring-cloud-gateway-adapter/src/test/java/com/alibaba/csp/sentinel/adapter/gateway/sc/SentinelGatewayFilterTest.java
  sentinel-adapter/sentinel-zuul-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/gateway/zuul/api/matcher/RequestContextApiMatcher.java
  sentinel-demo/sentinel-demo-spring-cloud-gateway/src/main/java/com/alibaba/csp/sentinel/demo/spring/sc/gateway/GatewayConfiguration.java
  sentinel-demo/sentinel-demo-zuul-gateway/src/main/java/com/alibaba/csp/sentinel/demo/zuul/gateway/GatewayRuleConfig.java
Labels: kind/feature, to review

#836 Add log to console support for common logs
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/log/ConsoleHandler.java
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/log/CspFormatter.java
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/log/LogBase.java
  sentinel-core/src/test/java/com/alibaba/csp/sentinel/log/ConsoleHandlerTest.java
Labels: area/log, to review

#854 Add unit tests for com.alibaba.csp.sentinel.eagleeye.EagleEyeCoreUtils
  sentinel-core/src/test/java/com/alibaba/csp/sentinel/eagleeye/EagleEyeCoreUtilsTest.java
Labels: area/test

#788 fix too many connection of zookeeper datasource
  sentinel-extension/sentinel-datasource-zookeeper/src/main/java/com/alibaba/csp/sentinel/datasource/zookeeper/ZookeeperDataSource.java
  sentinel-extension/sentinel-datasource-zookeeper/src/test/java/com/alibaba/csp/sentinel/datasource/zookeeper/ZookeeperDataSourceTest.java
Labels: kind/enhancement

#871 Modify variable names and Optimize methods
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/slotchain/SlotChainProvider.java
Labels: to review
