Repository alibaba/Sentinel, pull requests merged in 2019-01, with the labels that each got.

#380 Support multiple tokens per request entry
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/node/ClusterNode.java
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/node/DefaultNode.java
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/node/Node.java
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/node/StatisticNode.java
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/statistic/StatisticSlot.java
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/statistic/data/MetricBucket.java
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/statistic/metric/ArrayMetric.java
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/statistic/metric/Metric.java
  sentinel-core/src/test/java/com/alibaba/csp/sentinel/base/metric/ArrayMetricTest.java
  sentinel-core/src/test/java/com/alibaba/csp/sentinel/base/metric/MetricsLeapArrayTest.java
Labels: to review

#382 Add total QPS limit control for specific namespace in cluster flow control
  sentinel-cluster/sentinel-cluster-server-default/src/main/java/com/alibaba/csp/sentinel/cluster/flow/ClusterFlowChecker.java
  sentinel-cluster/sentinel-cluster-server-default/src/main/java/com/alibaba/csp/sentinel/cluster/flow/ClusterParamFlowChecker.java
  sentinel-cluster/sentinel-cluster-server-default/src/main/java/com/alibaba/csp/sentinel/cluster/flow/rule/ClusterFlowRuleManager.java
  sentinel-cluster/sentinel-cluster-server-default/src/main/java/com/alibaba/csp/sentinel/cluster/flow/rule/ClusterParamFlowRuleManager.java
  sentinel-cluster/sentinel-cluster-server-default/src/main/java/com/alibaba/csp/sentinel/cluster/flow/statistic/limit/GlobalRequestLimiter.java
  sentinel-cluster/sentinel-cluster-server-default/src/main/java/com/alibaba/csp/sentinel/cluster/flow/statistic/limit/RequestLimiter.java
  sentinel-cluster/sentinel-cluster-server-default/src/main/java/com/alibaba/csp/sentinel/cluster/server/command/handler/FetchClusterServerInfoCommandHandler.java
  sentinel-cluster/sentinel-cluster-server-default/src/main/java/com/alibaba/csp/sentinel/cluster/server/command/handler/ModifyClusterServerFlowConfigHandler.java
  sentinel-cluster/sentinel-cluster-server-default/src/main/java/com/alibaba/csp/sentinel/cluster/server/config/ClusterServerConfigManager.java
  sentinel-cluster/sentinel-cluster-server-default/src/main/java/com/alibaba/csp/sentinel/cluster/server/config/ServerFlowConfig.java
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/cluster/TokenResultStatus.java
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/block/flow/FlowRuleChecker.java
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/statistic/base/UnaryLeapArray.java
Labels: to review

#392 add blog with sentinel in action
  doc/awesome-sentinel.md
Labels: kind/document

#370 Make fallbackToLocalWhenFail be configurable in dashboard and fix edit rule issue when cancel
  sentinel-dashboard/src/main/webapp/resources/app/scripts/controllers/authority.js
  sentinel-dashboard/src/main/webapp/resources/app/scripts/controllers/degrade.js
  sentinel-dashboard/src/main/webapp/resources/app/scripts/controllers/flow_v1.js
  sentinel-dashboard/src/main/webapp/resources/app/scripts/controllers/flow_v2.js
  sentinel-dashboard/src/main/webapp/resources/app/scripts/controllers/param_flow.js
  sentinel-dashboard/src/main/webapp/resources/app/scripts/controllers/system.js
  sentinel-dashboard/src/main/webapp/resources/app/views/dialog/flow-rule-dialog.html
  sentinel-dashboard/src/main/webapp/resources/app/views/metric.html
Labels: dashboard, to review

#376 add healthCount/total for dashboard sidebar
  sentinel-dashboard/src/main/webapp/resources/app/scripts/directives/sidebar/sidebar.html
  sentinel-dashboard/src/main/webapp/resources/app/scripts/directives/sidebar/sidebar.js
Labels: to review

#398 p_qps and b_qps are not intuitive in monitoring curve of dashboard. Let's make it a little bit more intuitive in Chinese
  sentinel-dashboard/src/main/webapp/resources/app/scripts/controllers/metric.js
  sentinel-dashboard/src/main/webapp/resources/app/views/metric.html
Labels: to review

#188 Feature spring cloud zuul adapter
  sentinel-adapter/pom.xml
  sentinel-adapter/sentinel-zuul-adapter/README.md
  sentinel-adapter/sentinel-zuul-adapter/pom.xml
  sentinel-adapter/sentinel-zuul-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/zuul/constants/ZuulConstant.java
  sentinel-adapter/sentinel-zuul-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/zuul/fallback/BlockResponse.java
  sentinel-adapter/sentinel-zuul-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/zuul/fallback/DefaultBlockFallbackProvider.java
  sentinel-adapter/sentinel-zuul-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/zuul/fallback/DefaultRequestOriginParser.java
  sentinel-adapter/sentinel-zuul-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/zuul/fallback/DefaultUrlCleaner.java
  sentinel-adapter/sentinel-zuul-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/zuul/fallback/RequestOriginParser.java
  sentinel-adapter/sentinel-zuul-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/zuul/fallback/UrlCleaner.java
  sentinel-adapter/sentinel-zuul-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/zuul/fallback/ZuulBlockFallbackManager.java
  sentinel-adapter/sentinel-zuul-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/zuul/fallback/ZuulBlockFallbackProvider.java
  sentinel-adapter/sentinel-zuul-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/zuul/filters/AbstractSentinelFilter.java
  sentinel-adapter/sentinel-zuul-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/zuul/filters/SentinelErrorFilter.java
  sentinel-adapter/sentinel-zuul-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/zuul/filters/SentinelPostFilter.java
  sentinel-adapter/sentinel-zuul-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/zuul/filters/SentinelPreFilter.java
  sentinel-adapter/sentinel-zuul-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/zuul/properties/SentinelZuulProperties.java
  sentinel-adapter/sentinel-zuul-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/zuul/util/FilterUtil.java
  sentinel-adapter/sentinel-zuul-adapter/src/test/java/com/alibaba/csp/sentinel/adapter/zuul/fallback/ZuulBlockFallbackManagerTest.java
  sentinel-adapter/sentinel-zuul-adapter/src/test/java/com/alibaba/csp/sentinel/adapter/zuul/fallback/ZuulBlockFallbackProviderTest.java
  sentinel-adapter/sentinel-zuul-adapter/src/test/java/com/alibaba/csp/sentinel/adapter/zuul/filters/SentinelErrorFilterTest.java
  sentinel-adapter/sentinel-zuul-adapter/src/test/java/com/alibaba/csp/sentinel/adapter/zuul/filters/SentinelPostFilterTest.java
  sentinel-adapter/sentinel-zuul-adapter/src/test/java/com/alibaba/csp/sentinel/adapter/zuul/filters/SentinelPreFilterTest.java
Labels: to review

#412 Remove redundant semicolon in MetricWriter
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/node/metric/MetricWriter.java
Labels: to review

#422 When click the first-level menu, don't jump to the home page
  sentinel-dashboard/src/main/webapp/resources/app/scripts/directives/sidebar/sidebar.html
Labels: to review

#425 Fix typo in README of Sentinel Dubbo Demo
  sentinel-demo/sentinel-demo-dubbo/README.md
Labels: area/document, typo/format

#436 Upgrade Dubbo version in sentinel-demo-dubbo
  sentinel-demo/sentinel-demo-dubbo/pom.xml
Labels: to review

#457 fix error value type and rename variable
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/node/EntranceNode.java
Labels: to review

#464 Remove duplicate comment
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/block/flow/controller/WarmUpController.java
Labels: to review

#465 HashMap init optimize when adding new ClusterNode to cluster node map
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/clusterbuilder/ClusterBuilderSlot.java
Labels: to review

#449 Make build faster by reducing fixed waiting time in tests
  .travis.yml
  pom.xml
  sentinel-core/pom.xml
  sentinel-core/src/test/java/com/alibaba/csp/sentinel/AsyncEntryIntegrationTest.java
  sentinel-core/src/test/java/com/alibaba/csp/sentinel/base/metric/MetricsLeapArrayTest.java
  sentinel-core/src/test/java/com/alibaba/csp/sentinel/slots/block/flow/FlowPartialIntegrationTest.java
  sentinel-core/src/test/java/com/alibaba/csp/sentinel/slots/block/flow/controller/WarmUpControllerTest.java
  sentinel-core/src/test/java/com/alibaba/csp/sentinel/slots/logger/EagleEyeLogUtilTest.java
  sentinel-extension/sentinel-datasource-redis/pom.xml
  sentinel-extension/sentinel-datasource-redis/src/test/java/com/alibaba/csp/sentinel/datasource/redis/SentinelModeRedisDataSourceTest.java
  sentinel-extension/sentinel-datasource-redis/src/test/java/com/alibaba/csp/sentinel/datasource/redis/StandaloneRedisDataSourceTest.java
  sentinel-extension/sentinel-datasource-zookeeper/pom.xml
  sentinel-extension/sentinel-datasource-zookeeper/src/test/java/com/alibaba/csp/sentinel/datasource/zookeeper/ZookeeperDataSourceTest.java
Labels: to review

#423 Add some unit test for StatisticNode, ClusterNode and DefaultNodeBuilder class
  sentinel-core/src/test/java/com/alibaba/csp/sentinel/node/ClusterNodeTest.java
  sentinel-core/src/test/java/com/alibaba/csp/sentinel/node/DefaultNodeBuilderTest.java
  sentinel-core/src/test/java/com/alibaba/csp/sentinel/node/StatisticNodeTest.java
Labels: area/test, to review

#474 update nacos namespace demo and update nacos-sdk version
  sentinel-demo/sentinel-demo-nacos-datasource/src/main/java/com/alibaba/csp/sentinel/demo/datasource/nacos/NacosDataSourceDemo.java
  sentinel-extension/sentinel-datasource-nacos/pom.xml
Labels: kind/enhancement
