Repository alibaba/Sentinel, pull requests merged in 2019-09, with the labels that each got.

#1047 Add concrete exception message in AsyncEntry#cleanCurrentEntryInLocal
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/AsyncEntry.java
Labels: kind/enhancement, to review

#1050 Improve the checking logic of SystemRule and enhance SystemRuleManager
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/system/SystemRuleManager.java
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/system/SystemStatusListener.java
  sentinel-core/src/test/java/com/alibaba/csp/sentinel/slots/system/SystemRuleManagerTest.java
Labels: kind/enhancement, to review

#1051 The UrlCleaner description is more accurate
  sentinel-adapter/sentinel-web-servlet/README.md
Labels: area/document

#1057 Feature: 网关规则和自定义api规则动态修改增加对写数据源的支持
  sentinel-adapter/sentinel-api-gateway-adapter-common/src/main/java/com/alibaba/csp/sentinel/adapter/gateway/common/command/UpdateGatewayApiDefinitionGroupCommandHandler.java
  sentinel-adapter/sentinel-api-gateway-adapter-common/src/main/java/com/alibaba/csp/sentinel/adapter/gateway/common/command/UpdateGatewayRuleCommandHandler.java
Labels: area/gateway-flow-control, to review
