Repository alibaba/Sentinel, pull requests merged in 2019-05, with the labels that each got.

#732 Fix bugs of zookeeper flow rule dynamic publisher sample in Sentinel dashboard
  sentinel-dashboard/src/test/java/com/alibaba/csp/sentinel/dashboard/rule/zookeeper/FlowRuleZookeeperPublisher.java
Labels: area/dashboard

#730 [Feature]Add an extension to Sentinel internal statistics
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/Tracer.java
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/metric/extension/MetricCallbackInit.java
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/metric/extension/MetricExtension.java
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/metric/extension/MetricExtensionProvider.java
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/metric/extension/callback/MetricEntryCallback.java
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/metric/extension/callback/MetricExitCallback.java
  sentinel-core/src/main/resources/META-INF/services/com.alibaba.csp.sentinel.init.InitFunc
  sentinel-core/src/test/java/com/alibaba/csp/sentinel/metric/extension/callback/FakeMetricExtension.java
  sentinel-core/src/test/java/com/alibaba/csp/sentinel/metric/extension/callback/MetricEntryCallbackTest.java
  sentinel-core/src/test/java/com/alibaba/csp/sentinel/metric/extension/callback/MetricExitCallbackTest.java
Labels: kind/feature, to review

#737 Fix the bug that Chinese characters are garbled in ResponseBody of ZuulBlockFallbackProvider
  sentinel-adapter/sentinel-zuul-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/gateway/zuul/filters/SentinelZuulPreFilter.java
  sentinel-demo/sentinel-demo-zuul-gateway/src/main/java/com/alibaba/csp/sentinel/demo/zuul/gateway/ZuulConfig.java
Labels: to review

#749 Add cpu usage and system load to metric
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/Constants.java
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/system/SystemRuleManager.java
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/system/SystemStatusListener.java
  sentinel-transport/sentinel-transport-common/src/main/java/com/alibaba/csp/sentinel/command/handler/SendMetricCommandHandler.java
Labels: area/metrics

#765 fix sentinel-dashboard中test模块错误FlowRuleZookeeperProvider component name
  sentinel-dashboard/src/test/java/com/alibaba/csp/sentinel/dashboard/rule/zookeeper/FlowRuleZookeeperProvider.java
Labels: area/dashboard, to review

#770 Enhancement/highestcpuusage
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/system/SystemRuleManager.java
Labels: to review

#766 Add Exceptions to trace or ignore in Tracer
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/Tracer.java
  sentinel-core/src/test/java/com/alibaba/csp/sentinel/TracerTest.java
Labels: to review
