Repository alibaba/Sentinel, pull requests merged in 2019-10, with the labels that each got.

#1049 Support URL exclusion using UrlCleaner in Spring WebFlux adapter
  sentinel-adapter/sentinel-spring-webflux-adapter/README.md
  sentinel-adapter/sentinel-spring-webflux-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/spring/webflux/SentinelWebFluxFilter.java
  sentinel-adapter/sentinel-spring-webflux-adapter/src/test/java/com/alibaba/csp/sentinel/adapter/spring/webflux/SentinelWebFluxIntegrationTest.java
Labels: to review

#1018 Support Etcd datasource
  pom.xml
  sentinel-demo/pom.xml
  sentinel-demo/sentinel-demo-etcd-datasource/pom.xml
  sentinel-demo/sentinel-demo-etcd-datasource/src/main/java/com/alibaba/csp/sentinel/demo/datasource/etcd/EtcdConfigSender.java
  sentinel-demo/sentinel-demo-etcd-datasource/src/main/java/com/alibaba/csp/sentinel/demo/datasource/etcd/EtcdDataSourceDemo.java
  sentinel-extension/pom.xml
  sentinel-extension/sentinel-datasource-etcd/README.md
  sentinel-extension/sentinel-datasource-etcd/pom.xml
  sentinel-extension/sentinel-datasource-etcd/src/main/java/com/alibaba/csp/sentinel/datasource/etcd/EtcdConfig.java
  sentinel-extension/sentinel-datasource-etcd/src/main/java/com/alibaba/csp/sentinel/datasource/etcd/EtcdDataSource.java
  sentinel-extension/sentinel-datasource-etcd/src/test/java/com/alibaba/csp/sentinel/datasource/etcd/EtcdDataSourceTest.java
Labels: area/integrations, kind/feature, to review

#1078 Fix the bug that resource name displayed in ClusterNode-related command APIs for SphU.entry(method) is incorrect
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/slotchain/MethodResourceWrapper.java
Labels: to review

#1089 Fix hookOnCancel handing logic in SentinelReactorSubscriber
  sentinel-adapter/sentinel-reactor-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/reactor/SentinelReactorSubscriber.java
  sentinel-adapter/sentinel-reactor-adapter/src/test/java/com/alibaba/csp/sentinel/adapter/reactor/MonoSentinelOperatorIntegrationTest.java
Labels: to review

#1111 Add init parameter to support unifying web context name in Sentinel Web CommonFilter
  sentinel-adapter/sentinel-web-servlet/src/main/java/com/alibaba/csp/sentinel/adapter/servlet/CommonFilter.java
  sentinel-adapter/sentinel-web-servlet/src/test/java/com/alibaba/csp/sentinel/adapter/servlet/CommonFilterTest.java
  sentinel-adapter/sentinel-web-servlet/src/test/java/com/alibaba/csp/sentinel/adapter/servletcontext/CommonFilterContextTest.java
  sentinel-adapter/sentinel-web-servlet/src/test/java/com/alibaba/csp/sentinel/adapter/servletcontext/FilterContextConfig.java
  sentinel-adapter/sentinel-web-servlet/src/test/java/com/alibaba/csp/sentinel/adapter/servletcontext/TestContextApplication.java
  sentinel-adapter/sentinel-web-servlet/src/test/java/com/alibaba/csp/sentinel/adapter/servletcontext/TestContextController.java
Labels: kind/enhancement

#1115 Improve Node and Metric interface to support conditional metric retrieval
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/node/Node.java
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/node/StatisticNode.java
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/statistic/metric/ArrayMetric.java
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/statistic/metric/Metric.java
  sentinel-core/src/test/java/com/alibaba/csp/sentinel/slots/statistic/metric/ArrayMetricTest.java
Labels: kind/enhancement, to review
