Repository alibaba/Sentinel, pull requests merged in 2020-02, with the labels that each got.

#1293 Fix NPE in Tracer when context size exceeds the limit (#1184)
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/Tracer.java
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/context/Context.java
  sentinel-core/src/test/java/com/alibaba/csp/sentinel/TracerTest.java
Labels: to review

#1265 Add SPI for logger
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/log/CommandCenterLog.java
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/log/CommandCenterLogLogging.java
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/log/FormattingTuple.java
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/log/Level.java
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/log/LogBase.java
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/log/LogTarget.java
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/log/LogType.java
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/log/Logger.java
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/log/MessageFormatter.java
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/log/RecordLog.java
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/log/RecordLogLogging.java
  sentinel-core/src/test/java/com/alibaba/csp/sentinel/RecordLogTest.java
  sentinel-demo/pom.xml
  sentinel-demo/sentinel-demo-log-logback/pom.xml
  sentinel-demo/sentinel-demo-log-logback/src/main/java/com/alibaba/csp/sentinel/demo/log/logback/CommandCenterLogLoggerImpl.java
  sentinel-demo/sentinel-demo-log-logback/src/main/java/com/alibaba/csp/sentinel/demo/log/logback/RecordLogLoggerImpl.java
  sentinel-demo/sentinel-demo-log-logback/src/main/resources/META-INF/services/com.alibaba.csp.sentinel.log.Logger
  sentinel-demo/sentinel-demo-log-logback/src/main/resources/logback.xml
  sentinel-demo/sentinel-demo-log-logback/src/test/java/com/alibaba/csp/sentinel/demo/log/logback/CommandCenterLogTest.java
  sentinel-demo/sentinel-demo-log-logback/src/test/java/com/alibaba/csp/sentinel/demo/log/logback/RecordLogTest.java
Labels: area/log, to review

#1296 sentinel-apache-dubbo-adapter not compatible dubbo 2.7.5
  sentinel-adapter/sentinel-apache-dubbo-adapter/pom.xml
  sentinel-adapter/sentinel-apache-dubbo-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/dubbo/BaseSentinelDubboFilter.java
  sentinel-adapter/sentinel-apache-dubbo-adapter/src/test/java/com/alibaba/csp/sentinel/adapter/dubbo/DubboAppContextFilterTest.java
  sentinel-adapter/sentinel-apache-dubbo-adapter/src/test/java/com/alibaba/csp/sentinel/adapter/dubbo/SentinelDubboConsumerFilterTest.java
  sentinel-adapter/sentinel-apache-dubbo-adapter/src/test/java/com/alibaba/csp/sentinel/adapter/dubbo/SentinelDubboProviderFilterTest.java
Labels: area/integrations, to review

#926 Migrage the console server's specifying logic into transport-common
  sentinel-transport/sentinel-transport-common/src/main/java/com/alibaba/csp/sentinel/transport/config/TransportConfig.java
  sentinel-transport/sentinel-transport-common/src/test/java/com/alibaba/csp/sentinel/transport/config/TransportConfigTest.java
  sentinel-transport/sentinel-transport-netty-http/src/main/java/com/alibaba/csp/sentinel/transport/heartbeat/HttpHeartbeatSender.java
  sentinel-transport/sentinel-transport-netty-http/src/test/java/com/alibaba/csp/sentinel/transport/heartbeat/HttpHeartbeatSenderTest.java
  sentinel-transport/sentinel-transport-simple-http/src/main/java/com/alibaba/csp/sentinel/transport/heartbeat/SimpleHttpHeartbeatSender.java
Labels: kind/enhancement, to review
