Repository alibaba/Sentinel, pull requests merged in 2020-04, with the labels that each got.

#1377 Force api to fail if an incompitible fastjson found
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/util/VersionUtil.java
  sentinel-core/src/test/java/com/alibaba/csp/sentinel/util/VersionUtilTest.java
  sentinel-transport/sentinel-transport-common/src/main/java/com/alibaba/csp/sentinel/command/handler/ModifyRulesCommandHandler.java
Labels: dependencies, kind/enhancement, size/S, to-review

#1365 Set default log level to INFO of JDK logging and improve log info and comment in SpiLoader
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/log/jul/BaseJulLogger.java
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/DefaultSlotChainBuilder.java
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/util/SpiLoader.java
  sentinel-core/src/test/java/com/alibaba/csp/sentinel/util/SpiLoaderTest.java
Labels: area/log, kind/enhancement

#1367 控制台集群限流规则配置页面改进-集群规则隐藏高级配置项
  sentinel-dashboard/src/main/webapp/resources/app/views/dialog/flow-rule-dialog.html
Labels: area/dashboard

#1400 Bug fix in SC gateway adapter: Cookie value should be retrieved from request
  sentinel-adapter/sentinel-spring-cloud-gateway-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/gateway/sc/ServerWebExchangeItemParser.java
Labels: area/gateway-flow-control, area/integrations, kind/bug

#1396 support jax-rs
  sentinel-adapter/pom.xml
  sentinel-adapter/sentinel-jax-rs-adapter/README.md
  sentinel-adapter/sentinel-jax-rs-adapter/pom.xml
  sentinel-adapter/sentinel-jax-rs-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/jaxrs/SentinelJaxRsClientTemplate.java
  sentinel-adapter/sentinel-jax-rs-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/jaxrs/SentinelJaxRsProviderFilter.java
  sentinel-adapter/sentinel-jax-rs-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/jaxrs/config/SentinelJaxRsConfig.java
  sentinel-adapter/sentinel-jax-rs-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/jaxrs/exception/DefaultExceptionMapper.java
  sentinel-adapter/sentinel-jax-rs-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/jaxrs/fallback/DefaultSentinelJaxRsFallback.java
  sentinel-adapter/sentinel-jax-rs-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/jaxrs/fallback/SentinelJaxRsFallback.java
  sentinel-adapter/sentinel-jax-rs-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/jaxrs/future/FutureWrapper.java
  sentinel-adapter/sentinel-jax-rs-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/jaxrs/request/DefaultRequestOriginParser.java
  sentinel-adapter/sentinel-jax-rs-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/jaxrs/request/DefaultResourceNameParser.java
  sentinel-adapter/sentinel-jax-rs-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/jaxrs/request/RequestOriginParser.java
  sentinel-adapter/sentinel-jax-rs-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/jaxrs/request/ResourceNameParser.java
  sentinel-adapter/sentinel-jax-rs-adapter/src/test/java/com/alibaba/csp/sentinel/adapter/jaxrs/ClientFilterTest.java
  sentinel-adapter/sentinel-jax-rs-adapter/src/test/java/com/alibaba/csp/sentinel/adapter/jaxrs/ProviderFilterTest.java
  sentinel-adapter/sentinel-jax-rs-adapter/src/test/java/com/alibaba/csp/sentinel/adapter/jaxrs/TestApplication.java
  sentinel-adapter/sentinel-jax-rs-adapter/src/test/java/com/alibaba/csp/sentinel/adapter/jaxrs/TestResource.java
  sentinel-adapter/sentinel-jax-rs-adapter/src/test/resources/application-client.yml
  sentinel-adapter/sentinel-jax-rs-adapter/src/test/resources/application-provider.yml
  sentinel-demo/pom.xml
  sentinel-demo/sentinel-demo-jax-rs/pom.xml
  sentinel-demo/sentinel-demo-jax-rs/src/main/java/com/alibaba/csp/sentinel/demo/jaxrs/CustomExceptionMapper.java
  sentinel-demo/sentinel-demo-jax-rs/src/main/java/com/alibaba/csp/sentinel/demo/jaxrs/HelloEntity.java
  sentinel-demo/sentinel-demo-jax-rs/src/main/java/com/alibaba/csp/sentinel/demo/jaxrs/HelloResource.java
  sentinel-demo/sentinel-demo-jax-rs/src/main/java/com/alibaba/csp/sentinel/demo/jaxrs/JaxRsClientDemo.java
  sentinel-demo/sentinel-demo-jax-rs/src/main/java/com/alibaba/csp/sentinel/demo/jaxrs/JaxRsDemoApplication.java
  sentinel-demo/sentinel-demo-jax-rs/src/main/java/com/alibaba/csp/sentinel/demo/jaxrs/SentinelJaxRsConfig.java
  sentinel-demo/sentinel-demo-jax-rs/src/main/resources/application.properties
Labels: area/integrations, size/XXL

#1429 If the lock acquisition fails, an IllegalMonitorStateException will be thrown.
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/context/ContextUtil.java
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/node/ClusterNode.java
Labels: kind/bug

#1068 fix: Tracer does not trace exception to DefaultNode
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/Tracer.java
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/node/ClusterNode.java
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/node/DefaultNode.java
  sentinel-core/src/test/java/com/alibaba/csp/sentinel/node/ClusterNodeTest.java
Labels: to-review

#1412 [1191] Support configuring project.name via the properties file
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/config/SentinelConfig.java
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/config/SentinelConfigLoader.java
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/util/AppNameUtil.java
  sentinel-core/src/test/java/com/alibaba/csp/sentinel/ConfigPropertyHelper.java
  sentinel-core/src/test/java/com/alibaba/csp/sentinel/config/SentinelConfigTest.java
Labels: area/configuration, kind/enhancement, to-review

#1437 Update resolving logic of project name and polish SentinelConfig
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/config/SentinelConfig.java
  sentinel-core/src/test/java/com/alibaba/csp/sentinel/ConfigPropertyHelper.java
  sentinel-core/src/test/java/com/alibaba/csp/sentinel/config/SentinelConfigTest.java
Labels: area/configuration, kind/enhancement

#1441 [ISSUE #1439]Remoce duplicate code
  sentinel-dashboard/src/main/java/com/alibaba/csp/sentinel/dashboard/datasource/entity/MetricEntity.java
Labels: area/dashboard
