Repository alibaba/Sentinel, pull requests merged in 2020-05, with the labels that each got.

#1443 Fix the bug that cookie of the dashboard may have conflict with web applications under the same domain
  sentinel-dashboard/src/main/resources/application.properties
Labels: area/dashboard

#1372 Clear useless data in ParameterMetric for removed rules
  sentinel-adapter/sentinel-api-gateway-adapter-common/src/main/java/com/alibaba/csp/sentinel/adapter/gateway/common/rule/GatewayRuleManager.java
  sentinel-extension/sentinel-parameter-flow-control/src/main/java/com/alibaba/csp/sentinel/slots/block/flow/param/ParamFlowRuleManager.java
  sentinel-extension/sentinel-parameter-flow-control/src/main/java/com/alibaba/csp/sentinel/slots/block/flow/param/ParameterMetric.java
  sentinel-extension/sentinel-parameter-flow-control/src/test/java/com/alibaba/csp/sentinel/slots/block/flow/param/ParamFlowRuleManagerTest.java
Labels: kind/enhancement, to-review

#1456 Add OkHttp integration
  sentinel-adapter/pom.xml
  sentinel-adapter/sentinel-okhttp-adapter/README.md
  sentinel-adapter/sentinel-okhttp-adapter/pom.xml
  sentinel-adapter/sentinel-okhttp-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/okhttp/SentinelOkHttpInterceptor.java
  sentinel-adapter/sentinel-okhttp-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/okhttp/config/SentinelOkHttpConfig.java
  sentinel-adapter/sentinel-okhttp-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/okhttp/extractor/DefaultOkHttpResourceExtractor.java
  sentinel-adapter/sentinel-okhttp-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/okhttp/extractor/OkHttpResourceExtractor.java
  sentinel-adapter/sentinel-okhttp-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/okhttp/fallback/DefaultOkHttpFallback.java
  sentinel-adapter/sentinel-okhttp-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/okhttp/fallback/OkHttpFallback.java
  sentinel-adapter/sentinel-okhttp-adapter/src/test/java/com/alibaba/csp/sentinel/adapter/okhttp/SentinelOkHttpInterceptorTest.java
  sentinel-adapter/sentinel-okhttp-adapter/src/test/java/com/alibaba/csp/sentinel/adapter/okhttp/app/TestApplication.java
  sentinel-adapter/sentinel-okhttp-adapter/src/test/java/com/alibaba/csp/sentinel/adapter/okhttp/app/controller/TestController.java
  sentinel-adapter/sentinel-okhttp-adapter/src/test/java/com/alibaba/csp/sentinel/adapter/okhttp/config/SentinelOkHttpConfigTest.java
  sentinel-adapter/sentinel-okhttp-adapter/src/test/java/com/alibaba/csp/sentinel/adapter/okhttp/extractor/OkHttpResourceExtractorTest.java
  sentinel-adapter/sentinel-okhttp-adapter/src/test/java/com/alibaba/csp/sentinel/adapter/okhttp/fallback/OkHttpFallbackTest.java
  sentinel-demo/pom.xml
  sentinel-demo/sentinel-demo-okhttp/pom.xml
  sentinel-demo/sentinel-demo-okhttp/src/main/java/com/alibaba/csp/sentinel/demo/okhttp/OkHttpDemoApplication.java
  sentinel-demo/sentinel-demo-okhttp/src/main/java/com/alibaba/csp/sentinel/demo/okhttp/controller/OkHttpTestController.java
  sentinel-demo/sentinel-demo-okhttp/src/main/resources/application.properties
Labels: area/integrations

#1473 Fix historical version compatibility problem for auth check via localStorage
  sentinel-dashboard/src/main/webapp/resources/app/scripts/directives/header/header.js
  sentinel-dashboard/src/main/webapp/resources/dist/js/app.js
  sentinel-dashboard/src/main/webapp/resources/dist/js/app.vendor.js
Labels: area/dashboard, to-review

#1496 provide a predicate to check whether the throwable should be traced
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/Tracer.java
  sentinel-core/src/test/java/com/alibaba/csp/sentinel/TracerTest.java
Labels: kind/enhancement

#1501 add unit test for tuple2
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/util/function/Tuple2.java
  sentinel-core/src/test/java/com/alibaba/csp/sentinel/util/function/Tuple2Test.java
Labels: area/test, to-review

#1491 support param flow for complex param
  sentinel-extension/sentinel-parameter-flow-control/src/main/java/com/alibaba/csp/sentinel/slots/block/flow/param/ParamFlowArgument.java
  sentinel-extension/sentinel-parameter-flow-control/src/main/java/com/alibaba/csp/sentinel/slots/block/flow/param/ParamFlowChecker.java
  sentinel-extension/sentinel-parameter-flow-control/src/test/java/com/alibaba/csp/sentinel/slots/block/flow/param/ParamFlowCheckerTest.java
Labels: kind/enhancement, to-review

#1493 Support setting class-level defaultFallback for annotation extension
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/annotation/SentinelResource.java
  sentinel-extension/sentinel-annotation-aspectj/src/main/java/com/alibaba/csp/sentinel/annotation/aspectj/AbstractSentinelAspectSupport.java
  sentinel-extension/sentinel-annotation-aspectj/src/test/java/com/alibaba/csp/sentinel/annotation/aspectj/integration/SentinelAnnotationIntegrationTest.java
  sentinel-extension/sentinel-annotation-aspectj/src/test/java/com/alibaba/csp/sentinel/annotation/aspectj/integration/service/BarService.java
  sentinel-extension/sentinel-annotation-aspectj/src/test/java/com/alibaba/csp/sentinel/annotation/aspectj/integration/service/GlobalFallback.java
Labels: kind/enhancement, to-review

#1504 add unit test for tokenBucket
  sentinel-core/src/test/java/com/alibaba/csp/sentinel/eagleeye/TokenBucketTest.java
Labels: area/test
