Repository alibaba/Sentinel, pull requests merged in 2021-03, with the labels that each got.

#2064 Polish StatisticNode code comment
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/node/StatisticNode.java
Labels: area/document

#2032 Simplify enums: remove unnecessary code and reuse enum name
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/EntryType.java
  sentinel-transport/sentinel-transport-common/src/main/java/com/alibaba/csp/sentinel/transport/endpoint/Protocol.java
Labels: kind/enhancement

#1992 Fix #1986: Migrate Travis CI to GitHub Actions
  .github/workflows/ci.yml
Labels: area/ci

#1751 Support Redis cluster in Redis data-source extension
  sentinel-extension/sentinel-datasource-redis/README.md
  sentinel-extension/sentinel-datasource-redis/src/main/java/com/alibaba/csp/sentinel/datasource/redis/RedisDataSource.java
  sentinel-extension/sentinel-datasource-redis/src/main/java/com/alibaba/csp/sentinel/datasource/redis/config/RedisConnectionConfig.java
  sentinel-extension/sentinel-datasource-redis/src/test/java/com/alibaba/csp/sentinel/datasource/redis/ClusterModeRedisDataSourceTest.java
  sentinel-extension/sentinel-datasource-redis/src/test/java/com/alibaba/csp/sentinel/datasource/redis/RedisConnectionConfigTest.java
Labels: area/data-source, kind/enhancement
