Repository alibaba/Sentinel, pull requests merged in 2021-02, with the labels that each got.

#2006 chore: bump fastjson to 1.2.75
  pom.xml
Labels: dependencies

#2003 chore: bump snakeyaml jar version
  sentinel-cluster/sentinel-cluster-server-envoy-rls/pom.xml
Labels: dependencies

#1757 bugfix:rocketmq demo can not finish
  sentinel-demo/sentinel-demo-rocketmq/src/main/java/com/alibaba/csp/sentinel/demo/rocketmq/Constants.java
  sentinel-demo/sentinel-demo-rocketmq/src/main/java/com/alibaba/csp/sentinel/demo/rocketmq/PullConsumerDemo.java
  sentinel-demo/sentinel-demo-rocketmq/src/main/java/com/alibaba/csp/sentinel/demo/rocketmq/SyncProducer.java
Labels: area/example

#2028 Bump spring-core version to 5.1.18.RELEASE
  sentinel-adapter/sentinel-zuul2-adapter/pom.xml
Labels: dependencies

#2015 upgrade the netty version to 4.1.48.Final
  sentinel-cluster/pom.xml
Labels: dependencies

#2046 fix(dashboard): ${user.home} is resolved when maven package
  sentinel-dashboard/pom.xml
  sentinel-dashboard/src/main/resources/application.properties
Labels: area/dashboard, kind/enhancement

#2054 docs: sentinel document website
  README.md
Labels: area/document
