Repository alibaba/Sentinel, pull requests merged in 2021-09, with the labels that each got.

#2369 fix 404 blog url
  doc/awesome-sentinel.md
Labels: area/document

#2275 [feature] Expose jmx endpoint for sentinel.
  pom.xml
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/block/flow/FlowRuleManager.java
  sentinel-extension/pom.xml
  sentinel-extension/sentinel-metric-exporter/pom.xml
  sentinel-extension/sentinel-metric-exporter/src/main/java/com/alibaba/csp/sentinel/metric/MetricExporterInit.java
  sentinel-extension/sentinel-metric-exporter/src/main/java/com/alibaba/csp/sentinel/metric/collector/MetricCollector.java
  sentinel-extension/sentinel-metric-exporter/src/main/java/com/alibaba/csp/sentinel/metric/exporter/MetricExporter.java
  sentinel-extension/sentinel-metric-exporter/src/main/java/com/alibaba/csp/sentinel/metric/exporter/jmx/JMXMetricExporter.java
  sentinel-extension/sentinel-metric-exporter/src/main/java/com/alibaba/csp/sentinel/metric/exporter/jmx/MBeanRegistry.java
  sentinel-extension/sentinel-metric-exporter/src/main/java/com/alibaba/csp/sentinel/metric/exporter/jmx/MetricBean.java
  sentinel-extension/sentinel-metric-exporter/src/main/java/com/alibaba/csp/sentinel/metric/exporter/jmx/MetricBeanWriter.java
  sentinel-extension/sentinel-metric-exporter/src/main/java/com/alibaba/csp/sentinel/metric/exporter/jmx/MetricMXBean.java
  sentinel-extension/sentinel-metric-exporter/src/main/resources/META-INF/services/com.alibaba.csp.sentinel.init.InitFunc
  sentinel-extension/sentinel-metric-exporter/src/test/java/com/alibaba/cps/sentinel/metric/exporter/MBeanRegistryTest.java
Labels: to-review, kind/feature, area/metrics

#2253 [ISSUE #2243] Fix the logo problem when change the context-path of dashboard.
  sentinel-dashboard/src/main/webapp/resources/index.htm
  sentinel-dashboard/src/main/webapp/resources/index_dev.htm
Labels: area/dashboard
