Repository alibaba/Sentinel, pull requests merged in 2021-06, with the labels that each got.

#2163 Support private blockHandler/fallback method for @SentinelResource annotation
  sentinel-extension/sentinel-annotation-aspectj/src/main/java/com/alibaba/csp/sentinel/annotation/aspectj/AbstractSentinelAspectSupport.java
  sentinel-extension/sentinel-annotation-aspectj/src/test/java/com/alibaba/csp/sentinel/annotation/aspectj/integration/SentinelAnnotationIntegrationTest.java
  sentinel-extension/sentinel-annotation-aspectj/src/test/java/com/alibaba/csp/sentinel/annotation/aspectj/integration/service/FooService.java
Labels: area/annotation, kind/enhancement

#2234 Remove duplicate jar dependencies(aspectjweaver contains aspectjrt)
  sentinel-extension/sentinel-annotation-aspectj/pom.xml
Labels: dependencies

#2254 Add introduction to Alibaba sentinel blog
  doc/awesome-sentinel.md
Labels: area/document
