Repository alibaba/Sentinel, pull requests merged in 2022-03, with the labels that each got.

#2591 修复移除TokenServer失败的问题
  sentinel-dashboard/src/main/java/com/alibaba/csp/sentinel/dashboard/util/ClusterEntityUtils.java
Labels: area/dashboard

#2609 Fix the method isValidRule in GatewayRuleManager.class has a invalid …
  sentinel-adapter/sentinel-api-gateway-adapter-common/src/main/java/com/alibaba/csp/sentinel/adapter/gateway/common/rule/GatewayRuleManager.java
Labels: kind/bug

#2614 [Enhancement] perfect the javadoc in ApiPredicateItemVo and DegradeRule.
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/block/degrade/DegradeRule.java
  sentinel-dashboard/src/main/java/com/alibaba/csp/sentinel/dashboard/domain/vo/gateway/api/ApiPredicateItemVo.java
Labels: area/document
