Repository alibaba/Sentinel, pull requests merged in 2022-01, with the labels that each got.

#2519 将 listeners 更改为 CopyOnWriteArraySet
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/property/DynamicSentinelProperty.java
Labels: kind/enhancement

#2523 修复了 StatisticSlot类中fireExit参数传递丢失args 的问题
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/statistic/StatisticSlot.java
Labels: kind/bug

#2477 [ISSUE #2425] upgrade the nacos client version to 1.4.2.
  sentinel-dashboard/src/test/java/com/alibaba/csp/sentinel/dashboard/controller/gateway/GatewayApiControllerTest.java
  sentinel-dashboard/src/test/java/com/alibaba/csp/sentinel/dashboard/controller/gateway/GatewayFlowRuleControllerTest.java
  sentinel-extension/sentinel-datasource-nacos/pom.xml
Labels: dependencies

#2514 新增 csp.sentinel.log.level 启动配置项，可设置为OFF，进行关闭日志
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/log/LogBase.java
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/log/jul/BaseJulLogger.java
Labels: area/logging

#2483 fix degrade_service.js alert message issue 2476
  sentinel-dashboard/src/main/webapp/resources/app/scripts/services/degrade_service.js
Labels: area/dashboard

#2542 Add support for customizing ConfigurableRequestItemParser for SC gateway and Zuul adapter
  sentinel-adapter/sentinel-api-gateway-adapter-common/src/main/java/com/alibaba/csp/sentinel/adapter/gateway/common/param/ConfigurableRequestItemParser.java
  sentinel-adapter/sentinel-spring-cloud-gateway-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/gateway/sc/SentinelGatewayFilter.java
  sentinel-adapter/sentinel-zuul-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/gateway/zuul/filters/SentinelZuulPreFilter.java
  sentinel-adapter/sentinel-zuul2-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/gateway/zuul2/filters/inbound/SentinelZuulInboundFilter.java
Labels: area/gateway-flow-control

#2550 [ISSUE #2545] add the reademe file to module `sentinel-metric-exporter`
  sentinel-extension/sentinel-metric-exporter/README.md
Labels: area/document
