Repository alibaba/Sentinel, pull requests merged in 2022-11, with the labels that each got.

#2232 solved #66, support default degrade rule.
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/block/degrade/DefaultDegradeRuleManager.java
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/block/degrade/DefaultDegradeSlot.java
  sentinel-core/src/main/resources/META-INF/services/com.alibaba.csp.sentinel.slotchain.ProcessorSlot
  sentinel-core/src/test/java/com/alibaba/csp/sentinel/slots/DefaultSlotChainBuilderTest.java
  sentinel-core/src/test/java/com/alibaba/csp/sentinel/slots/block/degrade/CircuitBreakingIntegrationTest.java
  sentinel-core/src/test/java/com/alibaba/csp/sentinel/spi/SpiLoaderTest.java
Labels: to-review, kind/feature, area/circuit-breaking

#2948 Fix spelling mistakes(#2930)
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/eagleeye/EagleEye.java
Labels: typo-or-format

#2893 opt: 移除无用的代码
  sentinel-demo/sentinel-demo-basic/src/main/java/com/alibaba/csp/sentinel/demo/system/SystemGuardDemo.java
Labels: area/example

#2970 Add Dockerfile for dashboard with doc update
  sentinel-dashboard/Dockerfile
  sentinel-dashboard/README.md
Labels: area/dashboard

#2973 Replace deprecated set-state set-output GitHub Action's commands
  .github/workflows/ci.yml
Labels: area/ci

#2976 Update metrics name for monitor better select in JMX MetricBeanWriter
  sentinel-extension/sentinel-metric-exporter/src/main/java/com/alibaba/csp/sentinel/metric/exporter/jmx/MetricBeanWriter.java
Labels: kind/enhancement, area/metrics

#2980 Fix NPE in LogSlot#entry for recording rule ID
  sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/logger/LogSlot.java
Labels: kind/bug
